# Generated by Django 4.1.7 on 2023-03-20 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_courserating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='rating_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
