# Generated by Django 4.1.7 on 2023-03-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentcourseenrolment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrolment',
            old_name='status',
            new_name='is_paid',
        ),
    ]
