# Generated by Django 4.1.7 on 2023-03-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_teacher_photo'),
        ('students', '0010_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher'),
        ),
    ]
