# Generated by Django 4.1.7 on 2023-02-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
    ]
