# Generated by Django 4.1.7 on 2023-02-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rename_address_teacher_skills'),
    ]

    operations = [
    ]
