# Generated by Django 4.1.7 on 2023-02-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20230225_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
