# Generated by Django 4.1.7 on 2023-02-27 03:41

from django.db import migrations, models
import django.db.models.deletion
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_course_featured_img_course_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(null=True, upload_to=teachers.models.video_upload_path)),
                ('remarks', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_chapters', to='teachers.course')),
            ],
            options={
                'verbose_name_plural': 'Chapters',
            },
        ),
    ]
