# Generated by Django 4.1.7 on 2023-03-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacher_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
