# Generated by Django 4.1.7 on 2023-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
